Models/Locacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLocacao.Models
{
    public class Locacao
    {
        public virtual int Id { get; set; }
        public virtual Veiculo Veiculo { get; set; }
        public virtual bool IsLocado { get; set; }
        public virtual int Diaria { get; set; }
        public virtual int DataInicioLocacao { get; set; }
        public virtual int DataFimLocacao { get; set; }

    }
}

Models/Veiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLocacao.Models
{
    public class Veiculo
    {
        public virtual int Id { get; set; }
        public virtual string Marca { get; set; }
        public virtual string Modelo { get; set; }
        public virtual int Ano { get; set; }
        public virtual string Cor { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaLocacao.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/VeiculoController.cs
using SistemaLocacao.DAO;
using SistemaLocacao.Models;
using SistemaLocacao.ViewModel;
using System.Web.Mvc;

namespace SistemaLocacao.Controllers
{
    public class VeiculoController : Controller
    {

        private VeiculoVM _viewModel;
        private VeiculoDAO _dao;

        public VeiculoController()
        {
            _viewModel = new VeiculoVM();
            _dao = new VeiculoDAO();

            _viewModel.Message = "";
            _viewModel.Success = false;

        }

        // GET: Veiculo
        public ActionResult Index()
        {
            _viewModel.veiculoList = _dao.GetAll();

            return View(_viewModel);
        }

        public ActionResult Create()
        {
            return View(_viewModel);
        }

        public ActionResult Store(Veiculo Veiculo)
        {
            if (ValidaQuantidadeVeiculos())
            {
                _dao.SaveOrUpdate(Veiculo);

                PreencherDados("Veículo cadastrado com sucesso!");

                return View("Index", _viewModel);
            }


            PreencherDados("Apenas 5 Veículos pode ser cadastrados cadastrados!", false);

            return View("Index", _viewModel);


        }

        public ActionResult Edit(int id)
        {
            _viewModel.Veiculo = _dao.GetById(id);

            return View("Edit", _viewModel);

        }

        public ActionResult Update(Veiculo Veiculo)
        {
            _dao.SaveOrUpdate(Veiculo);

            PreencherDados("Veículo atualizado com sucesso!");

            return View("Index", _viewModel);
        }

        public ActionResult Delete(int id)
        {
            _dao.Delete(id);

            PreencherDados("Veículo deletado com sucesso!");

            return View("Index", _viewModel);
        }


       public void PreencherDados(string mensagem, bool success = true)
        {
            _viewModel.Message = mensagem;
            _viewModel.Success = success;

            _viewModel.veiculoList = _dao.GetAll();
        }

        public bool ValidaQuantidadeVeiculos()
        {
            var total = _dao.GetAll().Count;

            if(total >= 5)
            {
                return false;
            }

            return true;
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Veículos", "Index", "Veiculo")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Veiculo/Create.cshtml
@model SistemaLocacao.ViewModel.VeiculoVM

<h1>Cadastro de Veículos</h1>

@using (Html.BeginForm("Store", "Veiculo", FormMethod.Post))
{

    @Html.HiddenFor(model => model.Veiculo.Id)

    <div class="form-group">
        <label for="marca">Marca</label>
        @Html.TextBoxFor(model => model.Veiculo.Marca,
            new
            {
                @class = "form-control",
                placeHolder = "Marca",
                type = "text",
            })

    </div>

    <div class="form-group">
        <label for="Modelo">Modelo</label>
        @Html.TextBoxFor(model => model.Veiculo.Modelo,
           new
           {
               @class = "form-control",
               placeHolder = "Modelo",
               type = "text",
           })
    </div>

    <div class="form-group">
        <label for="Ano">Ano</label>
        @Html.TextBoxFor(Ano => Ano.Veiculo.Ano,
           new
           {
               @class = "form-control",
               placeHolder = "Ano",
               type = "text",
           })
    </div>

    <div class="form-group">
        <label for="Cor">Cor</label>
        @Html.TextBoxFor(Cor => Cor.Veiculo.Cor,
           new
           {
               @class = "form-control",
               placeHolder = "Cor",
               type = "text",
           })
    </div>

    <div class="form-group">
        @Html.ActionLink("Voltar", "Index", "Veiculo", null, new { @class = "btn btn-default" })
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
}

Views/Veiculo/Edit.cshtml
@model SistemaLocacao.ViewModel.VeiculoVM

<h1>Cadastro de Veículos</h1>

@using (Html.BeginForm("Update", "Veiculo", FormMethod.Post))
{

    @Html.HiddenFor(model => model.Veiculo.Id)

    <div class="form-group">
        <label for="marca">Marca</label>
        @Html.TextBoxFor(model => model.Veiculo.Marca,
            new
            {
                @class = "form-control",
                placeHolder = "Marca",
                type = "text",
            })

        @Html.HiddenFor(model => model.Veiculo.Marca)
    </div>

    <div class="form-group">
        <label for="Modelo">Modelo</label>
        @Html.TextBoxFor(model => model.Veiculo.Modelo,
           new
           {
               @class = "form-control",
               placeHolder = "Modelo",
               type = "text",
           })
    </div>

    <div class="form-group">
        <label for="Ano">Ano</label>
        @Html.TextBoxFor(Ano => Ano.Veiculo.Ano,
           new
           {
               @class = "form-control",
               placeHolder = "Ano",
               type = "text",
           })
    </div>

    <div class="form-group">
        <label for="Cor">Cor</label>
        @Html.TextBoxFor(Cor => Cor.Veiculo.Cor,
           new
           {
               @class = "form-control",
               placeHolder = "Cor",
               type = "text",
           })
    </div>

    <div class="form-group">
        @Html.ActionLink("Voltar", "Index", "Veiculo", null, new { @class = "btn btn-default" })
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
}

Views/Veiculo/Index.cshtml
@model SistemaLocacao.ViewModel.VeiculoVM

<h1>Veículos</h1>
<hr />

@if (Model.Message != "" && Model.Success)
{
    <div class="row">
        <div class="alert alert-success" role="alert">@Model.Message</div>
    </div>
}

@if(Model.Message != "" && Model.Success)
{
    <div class="row">
        <div class="alert alert-warning" role="alert">@Model.Message</div>
    </div>
}



<div class="container">
    <div class="row">
        @Html.ActionLink("Novo Veículo", "Create", "Veiculo", null, new { @class = "btn btn-primary" })
    </div>

    <br />

    <div class="row">
        <table class="table table-bordered">
            <tr>
                <th>Modelo</th>
                <th>Marca</th>
                <th>Cor</th>
                <th>Ano</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model.veiculoList)
            {
                <tr>
                    <td>@item.Modelo</td>
                    <td>@item.Marca</td>
                    <td>@item.Cor</td>
                    <td>@item.Ano</td>
                    <td class="col-lg-1">
                        @Html.ActionLink("Editar", "Edit/" + @item.Id, "Veiculo", null, new { @class = "btn btn-success" })
                    </td>
                    <td class="col-lg-1">
                        @Html.ActionLink("Deletar", "Delete/" + @item.Id, "Veiculo", null, new { @class = "btn btn-warning" })
                    </td>
                </tr>
            }

        </table>
    </div>

</div>